(##namespace
 ("ehwas-resolver#"
  not-found-resolver
  orelse-resolver
  make-guarded-resolver
  make-cached-resolver
  make-filesystem-resolver
  make-table-resolver
  with-index-resolver
  with-prefix-resolver
  allow-resolver
  deny-resolver
  ))
