(##namespace
 ("ehwas-request#"
  make-request
  http-request
  request-method
  request-uri-string
  request-uri
  request-version
  request-header
  request-port
  request-path
  request-uri-query
 ))