(##namespace
 ("encode-openssl#"
  ssl-v2-client-method
  ssl-v2-server-method
  ssl-v2-method
  ssl-v3-client-method
  ssl-v3-server-method
  ssl-v3-method
  tls-v1-client-method
  tls-v1-server-method
  tls-v1-method
  ssl-v23-client-method
  ssl-v23-server-method
  ssl-v23-method

  ssl-ctx-new
  ssl-ctx-use-certificate-file
  ssl-ctx-use-certificate-chain-file
  ssl-ctx-load-verify-locations
  ssl-ctx-use-private-key-file
  ssl-ctx-check-private-key
  ssl-ctx-free
  ssl-ctx-set-session-id-context
  ssl-ctx-set-session-cache-mode
  ssl-ctx-get-session-cache-mode

  ssl-new
  ssl-accept
  ssl-connect
  ssl-check-private-key
  ssl-get-ctx
  ssl-get-rbio
  ssl-get-wbio
  ssl-pending
  ssl-set-accept-state
  ssl-set-connect-state
  ssl-free
  ssl-shutdown
  ssl-clear
  ssl-get-shutdown
  ssl-set-shutdown
  ssl-read
  ssl-write
  ssl-set-bio
  SSL_FILETYPE_PEM

  bio-new
  bio-set
  bio-free
  bio-pending
  bio-read
  bio-write

  bio-s-mem

  err-get-error
  err-peek-error
  err-peek-last-error
  err-error-string
  
  ssl-get-error
  SSL_ERROR_NONE
  SSL_ERROR_SSL
  SSL_ERROR_WANT_READ
  SSL_ERROR_WANT_WRITE
  SSL_ERROR_WANT_X509_LOOKUP
  SSL_ERROR_SYSCALL
  SSL_ERROR_ZERO_RETURN
  SSL_ERROR_WANT_CONNECT
  SSL_ERROR_WANT_ACCEPT
  ))
