(include "common.scm")

(define (install)
  (install-ansuz)
  (install-database)
  (install-ehwas)
  (install-encode)
  (install-gebo)
  (install-laguz)
  (install-yera))

(define (install-ansuz)
  (assert-directory (string-append (dest-dir) "/ansuz"))
  (sh (cp)
      (string-append (src-dir) "/ansuz/*.scm")
      (string-append (dest-dir)"/ansuz"))
  
  (assert-directory (string-append (dest-dir) "/ansuz/sources"))
  (sh (cp)
      (string-append (src-dir) "/ansuz/sources/*.scm")
      (string-append (dest-dir)"/ansuz/sources"))
  
  (assert-directory (string-append (dest-dir) "/ansuz/re"))
  (sh (cp)
      (string-append (src-dir) "/ansuz/re/*.scm")
      (string-append (dest-dir)"/ansuz/re")))

(define (install-database)
  (assert-directory (string-append (dest-dir) "/database"))
  (sh (cp)
      (string-append (src-dir) "/database/*.scm")
      (string-append (dest-dir)"/database")))

(define (install-ehwas)
  (assert-directory (string-append (dest-dir) "/ehwas"))
  (sh (cp)
      (string-append (src-dir) "/ehwas/*.scm")
      (string-append (dest-dir)"/ehwas"))
  
  (assert-directory (string-append (dest-dir) "/ehwas/sessions"))
  (sh (cp)
      (string-append (src-dir) "/ehwas/sessions/*.scm")
      (string-append (dest-dir)"/ehwas/sessions"))

  (assert-directory (string-append (dest-dir) "/ehwas/sessions/sql"))
  (sh (cp)
      (string-append (src-dir) "/ehwas/sessions/sql/*.sql")
      (string-append (dest-dir)"/ehwas/sessions/sql")))

(define (install-encode)
  (assert-directory (string-append (dest-dir) "/encode"))
  (sh (cp)
      (string-append (src-dir) "/encode/*.scm")
      (string-append (dest-dir)"/encode")))

(define (install-gebo)
  (assert-directory (string-append (dest-dir) "/gebo"))
  (sh (cp)
      (string-append (src-dir) "/gebo/*.scm")
      (string-append (dest-dir)"/gebo"))
  
  (assert-directory (string-append (dest-dir) "/gebo/js"))
  (sh (cp)
      (string-append (src-dir) "/gebo/js/*.js")
      (string-append (dest-dir) "/gebo/js")))

(define (install-laguz)
  (assert-directory (string-append (dest-dir) "/laguz"))
  (sh (cp)
      (string-append (src-dir) "/laguz/*.scm")
      (string-append (dest-dir)"/laguz")))

(define (install-yera)
  (assert-directory (string-append (dest-dir) "/yera"))
  (sh (cp)
      (string-append (src-dir) "/yera/*.scm")
      (string-append (dest-dir)"/yera"))
  
  (assert-directory (string-append (dest-dir) "/yera/js"))
  (sh (cp)
      (string-append (src-dir) "/yera/js/*.js")
      (string-append (dest-dir) "/yera/js")))

(install)
